[build]
# Use Nixpacks Python builder and explicitly install backend dependencies
builder = "nixpacks"
buildCommand = "pip install -r api/requirements.txt"

[deploy]
# Removed preDeploy migrations (Base.metadata.create_all covers initial table creation). Re-add later if full Alembic needed.
startCommand = "uvicorn api.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "never"