[build]
# Use Nixpacks Python builder and explicitly install backend dependencies
builder = "nixpacks"
buildCommand = "cd api && pip install -r requirements.txt"

[deploy]
# Removed preDeploy migrations (Base.metadata.create_all covers initial table creation). Re-add later if full Alembic needed.
startCommand = "sh run_api.sh"
healthcheckPath = "/healthz"
healthcheckTimeout = 100
restartPolicyType = "never"