[build]
# Use Nixpacks Python builder and explicitly install backend dependencies
builder = "nixpacks"
buildCommand = "cd api && pip install -r requirements.txt"

[deploy]
# Removed preDeploy migrations (Base.metadata.create_all covers initial table creation). Re-add later if full Alembic needed.
startCommand = "sh -c 'if [ -d api ] && [ -f api/main.py ]; then TARGET=api.main:app; elif [ -f main.py ]; then TARGET=main:app; else echo \"Cannot locate main.py\" >&2; exit 1; fi; uvicorn $TARGET --host 0.0.0.0 --port ${PORT:-8000}'"
healthcheckPath = "/healthz"
healthcheckTimeout = 100
restartPolicyType = "never"