[build]
# Use Nixpacks Python builder and explicitly install backend dependencies
builder = "nixpacks"
buildCommand = "pip install -r api/requirements.txt"

[deploy]
# Run migrations before starting (optional). Comment out if not needed.
preDeployCommand = ["sh -c 'cd api && alembic upgrade head'"]
# Point uvicorn at the api.main module (main.py lives inside api/)
startCommand = "uvicorn api.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "never"